# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=6.1.6
group=com.teamremastered.endrem
java_version=21

# Common
minecraft_version=1.21.11
minecraft_version_end=1.21.11
mod_name=End Remastered
mod_author=Jack Bagel
mod_id=endrem
license=GNU LGPLv3
credits=Team Remastered
description=End Remastered makes your Minecraft experience more challenging by emphasizing the adventurous side of the game. \
\\nExploration is the main focus of End Remastered, and to reach the End and beat the Ender Dragon, you will have to find the 16 custom eyes by exploring vanilla structures and fighting vanilla bosses.
minecraft_version_range=[1.21, 1.22)

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.11-20251209.172050

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.11
parchment_version=2025.12.20

# The version of Fabric that is used, see https://fabricmc.net/develop/ for new versions
fabric_version=0.141.3+1.21.11
fabric_loader_version=0.19.2

# The version of NeoForge that is used, see https://neoforged.net/ for new versions
neoforge_version=21.11.42
neoforge_loader_version_range=[4,)

# Curseforge
curseforge_project_id=404183

# Modrinth
modrinth_project_id=ZJTGwAND

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false